### ISSUE TITLE
Streamline login code

### ISSUE THREAD

**Issue by joespam** [joespam/businessSite#18]
Currently there are two identical but separate forms to log in with. This is because I utterly failed to do it with the same box. I ran into trouble because I could not retrieve the form in javascript, nor set its action. I was supposed to beable to , but both $('#formname') and document.getDocumentById('formname') returned undefined, so I could not change the .action attribute. Could not figure out why.

Further, hitting submit results in a blank params array for unknown reasons. Need to resolve that as well.

**Comment by shehabnabil** [comment]
ive been unable tp pull yhe document on git
what was it,
git add, or git pull? and the name of the document, or was it git pull
original master?
what was it???

**Comment by joespam** [comment]
Hey, I had a look on how to get the repo. This command works. Just cd into
the place where you want your copy of the repo to be, then run

git clone https://github.com/joespam/businessSite.git

That will get you a git-ready to go copy of the repo. Just remember to git
add your changes when you get to a state where you're ready. And don't
forget to 'git pull' frequently to make sure your getting the most recent
copies of files. And of course when you commit and fix an issue, make sure
your command includes a bit that says 'fixes" or "closes #<issue number>".

Thanks again for hanging out with me today and the catapult!

Joe
